### ISSUE TITLE
the variable of generators

### ISSUE THREAD

**Issue by qzhu2017** [qzhu2017/crystallography#16]
@scottfredericks 
I have created a simple test.py as follows
```python
#from crystallography import molecular_crystal
#struc = molecular_crystal.molecular_crystal(36, ['H2O'], [4], 2.5)
#print(struc.struct)

from crystallography import crystal
struc = crystal.random_crystal(14, ['C'], [4], 1.5)
print(struc.struct)
#struc = crystal.random_crystal(36, ['C'], [4], 1.5)
#print(struc.struct)
```
If you execute this script for a couple of times, you will find sometimes python has the following complaints
```
qiangzhu@Qiangs-MBP:~/Desktop$ python 1.py 
/Users/qiangzhu/miniconda3/lib/python3.6/site-packages/pymatgen/io/cif.py:44: UserWarning: Please install optional dependency pybtex if youwant to extract references from CIF files.
  warnings.warn("Please install optional dependency pybtex if you"
Traceback (most recent call last):
  File "1.py", line 6, in <module>
    struc = crystal.random_crystal(14, ['C'], [4], 1.5)
  File "/Users/qiangzhu/miniconda3/lib/python3.6/site-packages/crystallography/crystal.py", line 1465, in __init__
    self.generate_crystal()
  File "/Users/qiangzhu/miniconda3/lib/python3.6/site-packages/crystallography/crystal.py", line 1582, in generate_crystal
    coords_toadd, good_merge = merge_coordinate(coords, cell_matrix, self.wyckoffs, self.sg, tol)
  File "/Users/qiangzhu/miniconda3/lib/python3.6/site-packages/crystallography/crystal.py", line 841, in merge_coordinate
    index = check_wyckoff_position(merged, sg, exact_translation=False, PBC=PBC, PB=PB)
  File "/Users/qiangzhu/miniconda3/lib/python3.6/site-packages/crystallography/crystal.py", line 1397, in check_wyckoff_position
    p = find_generating_point(points, generators, PBC=PBC)
NameError: name 'generators' is not defined
```

**Comment by scottfredericks** [comment]
@qzhu2017 
I believe the issue should be fixed now. I failed to define the variable "generators".
